apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: ml-kafka/producer:latest
          env:
            - name: KAFKA_BOOTSTRAP
              value: kafka-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: sensor-readings
            - name: INTERVAL_S
              value: "0.5"
            - name: ANOMALY_RATE
              value: "0.05"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
